// ========== Shared Types ====================================================

export type JWT = string;

/**
 * Challenge indicator value related to 3DS authentication.
 * Format: one of the following values:
 * - "01" - No preference
 * - "02" - No challenge requested
 * - "03" - Challenge requested (3DS Requestor Preference)
 * - "04" - Challenge requested (Mandate)
 * - "05" - No challenge requested (transactional risk analysis already performed)
 * - "06" - No challenge requested (data share only)
 * - "07" - No challenge requested (strong consumer authentication already performed)
 * - "08" - No challenge requested (use trust list exemption if no challenge required)
 * - "09" - Challenge requested (trust list prompt requested if challenge required)
 */
type ChallengeIndicator =
  | "01"
  | "02"
  | "03"
  | "04"
  | "05"
  | "06"
  | "07"
  | "08"
  | "09";

/**
 * Action code indicating the next step required by the DCF (Digital Card Facility).
 */
type DcfActionCode =
  | "COMPLETE"
  | "CHANGE_CARD"
  | "ADD_CARD"
  | "SWITCH_CONSUMER"
  | "CANCEL"
  | "ERROR";

/**
 * Represents the current status of the card in the SRC system.
 */
type CardStatus = "ACTIVE" | "SUSPENDED" | "EXPIRED" | "PENDING" | "CANCELLED";

// ========== Init ============================================================

/**
 * DPA (Digital Payment Application) registration data.
 */
export interface DpaData {
  /** * DPA identifier generated by the SRC system during registration.
   * Format: String, 64 bytes.
   */
  srcDpaId?: string;
  /** * Backward-compatible alias used in some SDK flows.
   */
  srciDpaId?: string;
  /** * Display name of the DPA to facilitate transaction authentication.
   */
  dpaPresentationName?: string;
  /** * The URI for the DPA website or application.
   */
  dpaUri?: string;
}

interface PaymentOptions {
  dpaDynamicDataTtlMinutes?: number;
  dynamicDataType?:
    | "CARD_APPLICATION_CRYPTOGRAM_SHORT_FORM"
    | "CARD_APPLICATION_CRYPTOGRAM_LONG_FORM"
    | "CARDHOLDER_AUTHENTICATION_CRYPTOGRAM"
    | "DYNAMIC_CARD_SECURITY_CODE";
  dpaPanRequested?: boolean;
}

interface TransactionAmount {
  /** The transaction amount. Required for the SRC system to facilitate authentication. */
  transactionAmount: string;
  /** Currency code associated with the transaction. */
  transactionCurrencyCode: string;
}

interface CustomInputData {
  checkoutOrchestrator?: "merchant";
  customFlowType?: "paymentsetting" | "withincheckout";
  paymentCardTypeSelected?: "CREDIT" | "DEBIT";
}

interface MethodAttributes {
  challengeIndicator?: ChallengeIndicator;
  otpValue?: string;
  stepUpIdentifier?: string;
}

interface AuthenticationMethods {
  /** Indicates to SRCi if Click to Pay needs to perform managed authentication. */
  authenticationMethodType:
    | "SMS_OTP"
    | "EMAIL_OTP"
    | "APP_AUTHENTICATION"
    | "3DS";
  /** The authentication subject. Generally should be set to CARDHOLDER. */
  authenticationSubject: "CONSUMER" | "CARD" | "CARDHOLDER";
  methodAttributes?: MethodAttributes;
}

interface AuthenticationPreferences {
  /** SRCi preferences related to authentication methods to facilitate authentication. */
  authenticationMethods: AuthenticationMethods[];
  /** Indicates whether the SRCi or merchant prefers an authenticated payload. */
  payloadRequested: "AUTHENTICATED" | "NON_AUTHENTICATED";
}

/**
 * Configuration parameters common to a DPA, overriding the system configuration created during registration.
 */
export interface DpaTransactionOptions {
  /** Preferred locale (e.g., en_US). Based on ISO 639-1 and ISO 3166-1 alpha-2. */
  dpaLocale?: string;
  /** Allowed billing countries in ISO-3166-1 alpha-2 standard code. */
  dpaAcceptedBillingCountries?: string[];
  /** Allowed shipping countries in ISO-3166-1 alpha-2 standard code. */
  dpaAcceptedShippingCountries?: string[];
  /** Required billing address verbosity level. */
  dpaBillingPreference?: "FULL" | "POSTAL_COUNTRY" | "NONE";
  /** Required shipping address verbosity level. */
  dpaShippingPreference?: "FULL" | "POSTAL_COUNTRY" | "NONE";
  /** Whether the consumer's full name is requested. */
  consumerNameRequested?: boolean;
  /** Whether the consumer's email address is requested. */
  consumerEmailAddressRequested?: boolean;
  /** Whether the consumer's phone number is requested. */
  consumerPhoneNumberRequested?: boolean;
  /** Whether the Consumer National identifier is requested. */
  consumerNationalIdentifierRequested?: boolean;
  /** Payment options requested by the DPA. */
  paymentOptions?: PaymentOptions;
  /** Whether the payment will be processed immediately after selection or after confirmation. */
  reviewAction?: "pay" | "continue";
  /** Optional review message to go with the action. */
  checkoutDescription?: string;
  /** Type of the transaction. Default is PURCHASE. */
  transactionType?: "PURCHASE" | "BILL_PAYMENT" | "MONEY_TRANSFER";
  /** Deprecated: Transaction instruction. */
  transactionInstruction?:
    | "RECURRING_PAYMENTS"
    | "SUBSCRIPTION_SERVICES"
    | "INSTALLMENTS";
  /** Deprecated: Maximum number of authorizations for installment payments. */
  numberOfPayments?: number;
  /** Deprecated: Original purchase date in UNIX epoch milliseconds. */
  purchaseDate?: number;
  /** Deprecated: End date for recurring authorizations in UNIX epoch milliseconds. */
  recurringEndDate?: number;
  /** Deprecated: Minimum days between recurring authorizations. */
  recurringFrequency?: number;
  /** The verbosity of the payload requested. */
  payloadTypeIndicator?:
    | "FULL"
    | "SUMMARY"
    | "PAYMENT"
    | "NON_PAYMENT"
    | "NONE";
  /** Amount of the transaction. Required for SRC system authentication facilitation. */
  transactionAmount?: TransactionAmount;
  /** Order identifier generated by the DPA. Format: UUID. */
  merchantOrderId?: string;
  /** Optional merchant category code (MCC). */
  merchantCategoryCode?: string;
  /** Merchant country code in ISO-3166-1 alpha-2. */
  merchantCountryCode?: string;
  /** Merchant name assigned by the Acquirer or Payment System. */
  merchantName?: string;
  /** Acquirer BIN used for authenticated flows. */
  acquirerBIN?: string;
  /** Acquirer merchant identifier assigned by the Acquirer. */
  acquirerMerchantId?: string;
  /** Recurring payment metadata when transaction is recurring. */
  recurringData?: {
    /** Recurring amount in minor units, e.g., 12345 for 123.45. */
    recurringAmount: string;
  };
  authenticatedCredentialRequested?: boolean;
  customInputData?: CustomInputData;
  authenticationPreferences?: AuthenticationPreferences;
}

export interface InitInput {
  /** Merchant-generated transaction id propagated through the SRC flow. */
  srciTransactionId: string;
  /** DPA identifier used to initialize the SDK. */
  srciDpaId: string;
  /** SRC initiator identifier from onboarding. */
  srcInitiatorId: string;
  /** Optional DPA registration metadata overriding registered defaults. */
  dpaData?: DpaData;
  /** Runtime transaction options for this session. */
  dpaTransactionOptions: DpaTransactionOptions;
}

// ========== Address & Consumer =============================================

export interface MaskedPhoneNumber {
  /** Country code format. */
  countryCode: string;
  /** Masked phone number representation. */
  phoneNumber: string;
}

export interface MaskedConsumerIdentity {
  /**
   * Identity provider. Default value is SRC when omitted.
   */
  identityProvider?: string | null;
  /**
   * Primary identity type in SRC profile.
   * Format: one of the following values:
   * - "EMAIL_ADDRESS"
   * - "MOBILE_PHONE_NUMBER"
   */
  identityType: "EMAIL_ADDRESS" | "MOBILE_PHONE_NUMBER";
  /** Masked value of email or mobile number for display purposes. */
  maskedIdentityValue: string;
}

/**
 * Masked information about the consumer for UI display purposes.
 */
export interface MaskedConsumer {
  countryCode: string;
  languageCode: string;
  dateConsumerAdded: string;
  emailAddress: string;
  firstName: string | null;
  fullName: string | null;
  lastName: string | null;
  maskedNationalIdentifier: string | null;
  maskedMobileNumber: MaskedPhoneNumber;
  srcConsumerId: string;
  status: string;
  maskedConsumerIdentity: MaskedConsumerIdentity;
}

export interface UriData {
  /** Uniform Resource Identifier (URI). */
  uri: string;
  uriType: "APP_URI" | "WEB_URI";
  challengeIndicator?: ChallengeIndicator;
  otpValue?: string;
  stepUpIdentifier?: string;
}

export interface AuthenticationMethod {
  /** Indicates to SRCi if managed authentication is needed. */
  authenticationMethodType:
    | "SMS_OTP"
    | "EMAIL_OTP"
    | "APP_AUTHENTICATION"
    | "MANAGED_AUTHENTICATION";
  /** Authentication subject. */
  authenticationSubject: "CARDHOLDER" | "CONSUMER" | "CARD";
  /** URI associated with the authentication method, if available. */
  uriData?: UriData;
  /** Masked credential reference for display (e.g., ***-***-1234). */
  authenticationCredentialReference?: string;
  /** Attributes related to the authentication method. */
  methodAttributes?: Record<string, unknown>;
}

export interface DigitalCardData {
  /** Current card status in the SRC system. */
  status: CardStatus;
  /** Presentation text created by the consumer to enable recognition of the PAN. */
  presentationName: string;
  /** Presentation text defined by the SRC programme that describes the PAN. */
  descriptorName: string;
  /** URI of the Art card application image. */
  artUri: string;
  /** Height of the Art card image in pixels. */
  artHeight: string;
  /** Width of the Art card image in pixels. */
  artWidth: string;
  /** Set of events that are pending completion (e.g., Device Binding). */
  pendingEvents: (
    | "PENDING_CONSUMER_IDV"
    | "PENDING_CONSUMER_DEVICE_BINDING"
    | "PENDING_CARDHOLDER_AUTHENTICATION"
  )[];
  authenticationMethod?: AuthenticationMethod;
  authenticationMethods?: AuthenticationMethod[];
}

export interface DCF {
  uri: string;
  logoUri: string;
  name: string;
}

export interface MaskedAddress {
  addressId?: string;
  line1?: string;
  line2?: string;
  line3?: string;
  city?: string;
  state?: string;
  zip?: string;
  countryCode: string;
}

/**
 * Address structure for billing or shipping.
 */
export interface Address {
  /** The address identifier in the SRC system. Format: UUID. */
  addressId?: string;
  /** The recipient name for the address, if known. Max 140 chars. */
  name?: string;
  /** Line 1 of the address. Conditional (Required if shipping). Max 140 chars. */
  line1?: string;
  /** Line 2 of the address. Max 140 chars. */
  line2?: string;
  /** Line 3 of the address. Max 140 chars. */
  line3?: string;
  /** City associated with the address. Conditional (Required if shipping). Max 100 chars. */
  city?: string;
  /** State associated with the address. Conditional. */
  state?: string;
  /** Zip/postal code. Conditional. 3-16 characters. */
  zip?: string;
  /** Country code. Required. Format: ISO-3166-1 alpha-2 standard code. */
  countryCode: string;
}

/**
 * Masked card information securely representing the actual PAN.
 */
export interface MaskedCard {
  srcDigitalCardId: string;
  panBin: string;
  panLastFour: string;
  tokenBinRange?: string;
  paymentAccountReference: string;
  tokenLastFour?: string;
  panExpirationMonth: string;
  panExpirationYear: string;
  digitalCardData: DigitalCardData;
  dateOfCardCreated: string;
  dateOfCardLastUsed?: string;
  maskedBillingAddress?: MaskedAddress;
  tokenId: string;
  paymentCardType: string;
}

interface SrcProfileMaskedConsumer {
  srcConsumerId: string;
  countryCode: string;
  languageCode: string;
  status: string;
  dateConsumerAdded: string;
  maskedConsumerIdentity: MaskedConsumerIdentity;
  maskedEmailAddress: string;
  maskedMobileNumber: string | null;
  maskedFirstName: string | null;
  maskedLastName: string | null;
  maskedFullName: string | null;
  maskedNationalIdentifier: string | null;
}

export interface SrcProfile {
  idToken: string;
  maskedCards: MaskedCard[];
  maskedConsumer: SrcProfileMaskedConsumer;
}

export interface GetSrcProfileInput {
  idTokens: JWT[];
}

export interface GetSrcProfileResponse {
  profiles?: SrcProfile[];
  srcCorrelationId?: string;
}

interface PhoneNumber {
  countryCode: string;
  phoneNumber: string;
}

interface ConsumerIdentity {
  /** Optional identifier of the identity provider. Default value is SRC. */
  identityProvider?: string;
  /** Raw consumer identity value used to locate info within the SRC profile. */
  identityValue: string;
  /** The type of the consumer identity. */
  identityType: "EMAIL_ADDRESS" | "MOBILE_PHONE_NUMBER";
}

/**
 * Data regarding the consumer involved in the transaction.
 */
export interface Consumer {
  /** Consumer's first name. Max 30 characters. */
  firstName?: string;
  /** Consumer's last name. Alphanumeric, 2-80 characters. */
  lastName?: string;
  /** Consumer's full name. Alphanumeric, 2-80 characters. */
  fullName?: string;
  /** Consumer's mobile phone number structure. */
  mobileNumber?: PhoneNumber;
  /** Consumer's valid email address. Max 255 characters. */
  emailAddress?: string;
  /** Consumer country code in ISO-3166-1 alpha-2 standard code. */
  countryCode?: string;
  /** Locale, based on ISO 639-1 and ISO 3166-1 alpha-2 (e.g., en_US). */
  languageCode?: string;
  /** Primary verifiable consumer identifier within an SRC Profile. */
  consumerIdentity?: ConsumerIdentity;
  /** Geographic specific, nationally-provided identifier for the Consumer. Max 20 chars. */
  nationalIdentifier?: string;
}

// ========== Compliance ======================================================

interface ComplianceResource {
  /** The type of compliance resource provided. */
  complianceType: "TERMS_AND_CONDITIONS" | "PRIVACY_POLICY" | "REMEMBER_ME";
  /** Uniform Resource Identifier (URI), a valid web address or URL. Max 1024 chars. */
  uri: string;
}

export interface ComplianceSettings {
  /** One or more compliance resources. */
  complianceResources: ComplianceResource[];
}

// ========== Checkout ========================================================

interface VerificationData {
  /** Type of assurance object returned by SRC. */
  verificationType: "CARDHOLDER";
  /**
   * Entity that performed verification.
   * Format: one of the following values:
   * - "02" - SRC Initiator (SRCi)
   * - "03" - SRC Profile/Payment Interface (SRCPI)
   */
  verificationEntity: "02" | "03";
  /**
   * Events that triggered verification.
   * - "01" - Payment transaction
   */
  verificationEvents: "01"[];
  /**
   * Verification method code.
   * - "01" - EMV 3-D Secure ACS
   * - "02" - App-based authentication
   * - "04" - One-time passcode
   * - "07" - FIDO
   */
  verificationMethod: "01" | "02" | "04" | "07";
  /** Verification result code. "01" - Verified. */
  verificationResults: "01";
  /** UTC timestamp in epoch-millis string format. */
  verificationTimestamp: string;
  /** Method-specific result payload (3DS and issuer extensions). */
  methodResults?: Record<string, unknown>;
  transStatus?: "Y" | "R" | "C" | "N" | "U" | "A" | "D" | "I";
  dsTransId?: string;
  acsTransId?: string;
}

/**
 * Information about any risk assessment operations performed by the SRC system.
 */
interface AssuranceData {
  /** Set of verification data structures relating to distinct types of assurance. */
  verificationData: VerificationData[];
  /**
   * Electronic Commerce Indicator (ECI) indicating the result of the authentication.
   * - "05" - Successful authentication
   * - "06" - Authentication attempted
   * - "07" - Authentication not performed
   */
  eci?: "05" | "06" | "07";
}

export interface CheckoutInput {
  /** SRC correlation id for continuing an existing flow. */
  srcCorrelationId?: string;
  /** Merchant transaction id. */
  srciTransactionId: string;
  /** Selected digital card id for checkout. */
  srcDigitalCardId?: string;
  /** Encrypted card payload for card enrollment/guest path. */
  encryptedCard?: string;
  /** SRC id token identifying consumer profile. */
  idToken?: string;
  /** SDK-managed popup/iframe reference. */
  windowRef?: Window | null;
  /** Per-transaction DPA overrides for checkout. */
  dpaTransactionOptions?: DpaTransactionOptions;
  /** Consumer data used for enrollment or enrichment. */
  consumer?: Consumer;
  /** Compliance disclosures accepted in this flow. */
  complianceSettings?: ComplianceSettings;
  /** Optional shipping address to include in transaction context. */
  shippingAddress?: Address;
  /** Optional authentication assurance metadata. */
  assuranceData?: AssuranceData;
  /** Encrypted billing address payload when required by setup. */
  encryptedBillingAddress?: string;
  /** Checkout action code, e.g. NEW_USER. */
  srciActionCode?: "NEW_USER" | string;
}
export interface CheckoutOutput {
  dcfActionCode: DcfActionCode;
  checkoutResponse?: CheckoutResponse;
  unbindAppInstance: boolean;
  idToken: string;
  recognitionToken?: string;
}
interface CheckoutResponse {
  srcCorrelationId: string;
  /** * A unique transaction ID created by the SRCi. Max 100 characters.
   */
  srciTransactionId: string;
  /** Masked card information securely representing the PAN. */
  maskedCard: MaskedCard;
  /** Zip code of the address being shipped to. */
  shippingAddressZip?: string;
  /** Country code of the address being shipped to (ISO-3166-1 alpha-2). */
  shippingCountryCode?: string;
  /** Masked information about the consumer for display purposes. */
  maskedConsumer: MaskedConsumer;
  /** Encrypted payload to be given to the merchant. Returned when PCI/PII is requested. */
  encryptedPayload?: string;
  /** Information about any risk assessment operations performed by the SRC system. */
  assuranceData?: AssuranceData;
  /** Whether the consumer checked out as a guest. Defaults to false. */
  isGuestCheckout: boolean;
  /** Whether the consumer enrolled during checkout in this transaction. Defaults to false. */
  isNewUser: boolean;
}

// ========== SDK method request / response pairs =============================
export interface IsRecognizedRequest {
  recognitionTokens?: JWT[];
  idTokens?: JWT[];
}
export interface IsRecognizedResponse {
  recognized: boolean;
  idTokens?: JWT[];
}

export interface IdentityLookupRequest {
  /** Consumer identity value used for lookup (email or mobile). */
  identityValue: string;
  /** Canonical field name used by docs structures. */
  identityType?: "EMAIL_ADDRESS" | "MOBILE_PHONE_NUMBER";
  /** Optional identity provider; defaults to SRC when omitted. */
  identityProvider?: string;
}

export interface IdentityLookupResponse {
  /** Whether a consumer profile was found for provided identity. */
  consumerPresent: boolean;
}

export interface InitiateIdentityValidationResponse {
  /** Masked channel representation, e.g. ***@mail.com / ********1234. */
  maskedValidationChannel: string;
}

export interface CompleteIdentityValidationInput {
  /** OTP or validation code entered by consumer. */
  validationData: string;
}

export interface CompleteIdentityValidationResponse {
  /** ID token issued after successful identity validation. */
  idToken: JWT;
}

interface UnbindAppInstanceInput {
  idToken?: JWT;
}

export interface UnbindAppInstanceResponse {
  /** Correlation id for unbind operation tracing. */
  srcCorrelationId: string;
}

// ========== SDK interface ===================================================

export interface VisaSdk {
  init: (initData: InitInput) => Promise<void>;

  identityLookup: (
    consumerIdentity: IdentityLookupRequest
  ) => Promise<IdentityLookupResponse>;

  initiateIdentityValidation: () => Promise<InitiateIdentityValidationResponse>;

  completeIdentityValidation: (
    validationData: CompleteIdentityValidationInput
  ) => Promise<CompleteIdentityValidationResponse>;

  getSrcProfile: (request: {
    idTokens: JWT[];
  }) => Promise<GetSrcProfileResponse>;

  isRecognized: (
    request?: IsRecognizedRequest
  ) => Promise<IsRecognizedResponse>;

  checkout: (data: CheckoutInput) => Promise<CheckoutOutput>;

  unbindAppInstance: (
    data: UnbindAppInstanceInput
  ) => Promise<UnbindAppInstanceResponse>;
}

declare global {
  interface Window {
    vAdapters?: {
      VisaSRCI: new () => VisaSdk;
    };
    SRCSDK_VISA?: VisaSdk;
  }
}
